token: 'MTI4MzkzNzAxNDY1OTU1MTI4Mw.GFZC5J.SJlqD6_dDEJ4AEzsyZz57j6jWEi5mdkikFwg5Q'
clientId: '1283937014659551283'
guildId: '1278190267370831925' # Para comandos de guilda, ou deixe vazio para comandos globais
embedColor: '#FF4500'
